const fa=n=>String(n??0).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]).replace(/,/g,'٬');
const norm=s=>String(s||'').toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim();
const products=window.FIRAN_PRODUCTS||[];
let cart=[];try{cart=JSON.parse(localStorage.getItem('firanCart')||'[]')}catch{cart=[]}
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('firanCart',JSON.stringify(cart));updateBadges();renderCart();}
function price(p){return Number(p.price)>0?fa(Number(p.price).toLocaleString('en-US'))+' تومان':'استعلام قیمت';}
function stock(p){return Math.max(0,Number(p.stock??10));}
function updateBadges(){const n=cart.reduce((a,x)=>a+Math.max(0,Number(x.qty)||0),0);document.querySelectorAll('[data-cart-count]').forEach(el=>{el.textContent=fa(n);el.hidden=n<=0;});}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;if(stock(p)<=0){alert('این کالا فعلاً ناموجود است.');return;}const x=cart.find(i=>i.id===id);if(x){if(x.qty>=stock(p)){alert('بیشتر از موجودی قابل افزودن نیست.');return;}x.qty++}else cart.push({id,qty:1});save();location.href='cart.html';}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);save();}
function changeQty(id,d){const x=cart.find(i=>i.id===id);const p=products.find(y=>y.id===id);if(!x||!p)return;const next=x.qty+d;if(next>stock(p)){alert('تعداد درخواستی بیشتر از موجودی است.');return;}x.qty=next;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save();}
function cartData(){let total=0;const items=cart.map(x=>{const p=products.find(y=>y.id===x.id);if(!p||stock(p)<=0)return null;const quantity=Math.min(stock(p),Math.max(1,Number(x.qty)||1));if(Number(p.price)>0)total+=Number(p.price)*quantity;return{...p,quantity}}).filter(Boolean);return{items,total};}
function renderCart(){const box=$('cartItems');if(!box)return;const {items,total}=cartData();if(!items.length){box.innerHTML='<div class="empty small"><h3>سبد خرید شما خالی است.</h3><a class="btn primary" href="products.html">مشاهده کالاها</a></div>';if($('cartTotal'))$('cartTotal').textContent='۰ تومان';if($('checkoutBtn'))$('checkoutBtn').disabled=true;return;}if($('checkoutBtn'))$('checkoutBtn').disabled=false;box.innerHTML=items.map(p=>`<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div class="cart-item-info"><b>${p.name}</b><small>${p.brand} • ${price(p)} • موجودی: ${fa(stock(p))}</small></div><div class="qty"><button type="button" onclick="changeQty('${p.id}',-1)">−</button><b>${fa(p.quantity)}</b><button type="button" onclick="changeQty('${p.id}',1)">+</button></div><button class="remove" type="button" onclick="removeFromCart('${p.id}')">حذف</button></div>`).join('');if($('cartTotal'))$('cartTotal').textContent=fa(total.toLocaleString('en-US'))+' تومان';if($('inquiryNotice'))$('inquiryNotice').hidden=!items.some(x=>Number(x.price)<=0);}
function card(p){const available=stock(p)>0;return `<article class="card"><a href="product.html?id=${encodeURIComponent(p.id)}" class="pic"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge ${available?'':'danger'}">${available?'موجود':'ناموجود'}</span></a><div class="card-body"><small>${p.brand} • ${p.categoryFa}</small><h3>${p.name}</h3><p>${p.model}</p><strong class="price">${price(p)}</strong><small class="stock-line">موجودی: ${fa(stock(p))}</small><div class="card-actions"><a class="btn outline" href="product.html?id=${encodeURIComponent(p.id)}">جزئیات</a><button class="btn primary" ${available?'':'disabled'} onclick="addToCart('${p.id}')">${available?'افزودن به سبد':'ناموجود'}</button></div></div></article>`;}
function fillBrands(){const b=$('brandFilter');if(!b)return;const brands=[...new Set(products.map(p=>p.brand))].sort((a,z)=>a.localeCompare(z));b.innerHTML='<option value="all">همه برندها</option>'+brands.map(x=>`<option value="${x}">${x}</option>`).join('');}
function filterProducts(){const grid=$('productsGrid');if(!grid)return;const q=norm($('searchInput')?.value),cat=$('categoryFilter')?.value||'all',brand=$('brandFilter')?.value||'all',min=+$('minPrice')?.value||0,max=+$('maxPrice')?.value||Infinity,priced=$('onlyPriced')?.checked,sort=$('sortFilter')?.value||'default';let a=products.filter(p=>{const hay=norm([p.name,p.brand,p.model,p.categoryFa,p.keywords,p.desc].join(' '));return(!q||hay.includes(q))&&(cat==='all'||p.category===cat)&&(brand==='all'||p.brand===brand)&&(!priced||p.price>0)&&(p.price===0||p.price>=min)&&(p.price===0||p.price<=max)});if(sort==='priceAsc')a.sort((x,y)=>(x.price||Infinity)-(y.price||Infinity));if(sort==='priceDesc')a.sort((x,y)=>(y.price||-1)-(x.price||-1));if(sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'fa'));grid.innerHTML=a.map(card).join('');if($('emptyState'))$('emptyState').hidden=!!a.length;if($('resultCount'))$('resultCount').textContent=fa(a.length)+' کالا';}
function setupSearch(){if(!$('productsGrid'))return;fillBrands();['searchInput','categoryFilter','brandFilter','minPrice','maxPrice','sortFilter','onlyPriced'].forEach(id=>$(id)?.addEventListener('input',filterProducts));document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{$('searchInput').value=b.dataset.q;filterProducts()}));$('clearSearch')?.addEventListener('click',()=>{$('searchInput').value='';filterProducts()});$('resetFilters')?.addEventListener('click',()=>{['searchInput','minPrice','maxPrice'].forEach(id=>$(id).value='');$('categoryFilter').value='all';$('brandFilter').value='all';$('sortFilter').value='default';$('onlyPriced').checked=false;filterProducts()});filterProducts();}
function setupCheckout(){const form=$('checkoutForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const {items,total}=cartData();if(!items.length)return alert('سبد خرید شما خالی است.');const customer={name:$('customerName').value.trim(),phone:$('customerPhone').value.trim(),address:$('customerAddress').value.trim()};if(!customer.name||!customer.phone||!customer.address)return alert('لطفاً نام، شماره تماس و آدرس را کامل کنید.');const payment=document.querySelector('input[name="payment"]:checked')?.value||'cod';const result=$('orderResult');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,payment,items:items.map(x=>({id:x.id,quantity:x.quantity}))})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.success)throw new Error(data.message||'ثبت سفارش انجام نشد');localStorage.setItem('firanLastOrder',JSON.stringify({orderId:data.orderId,total:Number(data.total||total),inquiry:Boolean(data.inquiry),createdAt:new Date().toISOString()}));cart=[];save();location.href='order-success.html';}catch(err){console.error(err);if(result){result.hidden=false;result.textContent='ثبت سفارش انجام نشد: '+err.message;}else alert(err.message);}});}
function setupCartButtons(){$('checkoutBtn')?.addEventListener('click',()=>{if(cartData().items.length)location.href='checkout.html';});}
function showSuccess(){const data=JSON.parse(localStorage.getItem('firanLastOrder')||'null');if(!data)return;if($('orderId'))$('orderId').textContent=data.orderId||'ثبت شد';if($('orderAmount'))$('orderAmount').textContent=data.inquiry?'استعلام قیمت':fa(Number(data.total||0).toLocaleString('en-US'))+' تومان';if($('orderInquiry'))$('orderInquiry').hidden=!data.inquiry;}
function init(){updateBadges();renderCart();setupSearch();setupCheckout();setupCartButtons();showSuccess();}
document.addEventListener('DOMContentLoaded',init);window.addToCart=addToCart;window.removeFromCart=removeFromCart;window.changeQty=changeQty;