const express=require('express');
const fs=require('fs');const path=require('path');const crypto=require('crypto');
require('dotenv').config();
const products=require('./catalog');const {getBotReply}=require('./bot');
const app=express();const PORT=Number(process.env.PORT||3000);
const ORDERS_FILE=path.join(__dirname,'orders.json'),REVIEWS_FILE=path.join(__dirname,'reviews.json'),INVENTORY_FILE=path.join(__dirname,'inventory.json');
const BACKUP_DIR=path.join(__dirname,'backups');
const ADMIN_USERNAME=process.env.ADMIN_USERNAME||'admin',ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'CHANGE_ME',SESSION_SECRET=process.env.SESSION_SECRET||'CHANGE_ME_LONG_SECRET';
const sessions=new Map(),SESSION_DURATION=8*60*60*1000,loginAttempts=new Map();
const productMap=new Map(products.map(p=>[String(p.id),p]));const validProducts=[...productMap.keys()];
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
function ensure(file,d=[]){if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(d,null,2),'utf8')}
ensure(ORDERS_FILE,[]);ensure(REVIEWS_FILE,[]);ensure(INVENTORY_FILE,Object.fromEntries(products.map(p=>[p.id,Number(p.stock??0)])));if(!fs.existsSync(BACKUP_DIR))fs.mkdirSync(BACKUP_DIR,{recursive:true});
function readJson(file,f=[]){try{const s=fs.readFileSync(file,'utf8');return s.trim()?JSON.parse(s):f}catch(e){console.error('JSON read error',e.message);return f}}
function writeJson(file,d){const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(d,null,2),'utf8');fs.renameSync(tmp,file)}
function backupData(){const stamp=new Date().toISOString().replace(/[:.]/g,'-');const file=path.join(BACKUP_DIR,`backup-${stamp}.json`);fs.writeFileSync(file,JSON.stringify({createdAt:new Date().toISOString(),orders:readJson(ORDERS_FILE,[]),reviews:readJson(REVIEWS_FILE,[])},null,2),'utf8');return file}
function orderId(){const d=new Date();const date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return`FK-${date}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`}
function reviewId(){return`REV-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`}
function createSession(username){const t=crypto.createHmac('sha256',SESSION_SECRET).update(username+Date.now()+crypto.randomBytes(8).toString('hex')).digest('hex');sessions.set(t,{username,createdAt:Date.now()});return t}
function getSession(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)firan_admin_session=([^;]+)/);if(!m)return null;const s=sessions.get(m[1]);if(!s)return null;if(Date.now()-s.createdAt>SESSION_DURATION){sessions.delete(m[1]);return null}return{token:m[1],...s}}
function requireAdmin(req,res,next){const s=getSession(req);if(!s)return res.status(401).json({success:false,message:'دسترسی غیرمجاز است.'});req.admin=s;next()}
function loginAllowed(ip){const now=Date.now(),a=loginAttempts.get(ip)||[];const fresh=a.filter(t=>now-t<10*60*1000);loginAttempts.set(ip,fresh);return fresh.length<8}
function recordLoginFail(ip){const a=loginAttempts.get(ip)||[];a.push(Date.now());loginAttempts.set(ip,a)}
app.post('/api/bot/chat',(req,res)=>{try{res.json({success:true,reply:getBotReply(String(req.body?.message||'').trim())})}catch(e){console.error(e);res.status(500).json({success:false,reply:'متأسفانه مشکلی پیش آمد.'})}});
app.post('/api/admin/login',(req,res)=>{const ip=req.ip;if(!loginAllowed(ip))return res.status(429).json({success:false,message:'تعداد تلاش‌های ورود زیاد است. چند دقیقه بعد دوباره امتحان کنید.'});const u=String(req.body.username||'').trim(),p=String(req.body.password||'');if(u!==ADMIN_USERNAME||p!==ADMIN_PASSWORD){recordLoginFail(ip);return res.status(401).json({success:false,message:'نام کاربری یا رمز عبور اشتباه است.'});}loginAttempts.delete(ip);const t=createSession(u);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`firan_admin_session=${t}; HttpOnly; Path=/; SameSite=Strict; Max-Age=${SESSION_DURATION/1000}${secure}`);res.json({success:true})});
app.post('/api/admin/logout',(req,res)=>{const s=getSession(req);if(s)sessions.delete(s.token);res.setHeader('Set-Cookie','firan_admin_session=; HttpOnly; Path=/; SameSite=Strict; Max-Age=0');res.json({success:true})});
app.get('/api/admin/session',(req,res)=>{const s=getSession(req);res.json(s?{loggedIn:true,username:s.username}:{loggedIn:false})});
app.get('/api/products',(req,res)=>{const inv=readJson(INVENTORY_FILE,{});res.json({success:true,products:products.map(p=>({id:p.id,name:p.name,brand:p.brand,category:p.category,categoryFa:p.categoryFa,price:p.price,image:p.image,stock:Number(inv[p.id]??0)}))});});
app.post('/api/orders',(req,res)=>{try{const {customer,payment,items}=req.body;if(!customer||typeof customer!=='object'||!Array.isArray(items)||!items.length)return res.status(400).json({success:false,message:'اطلاعات سفارش ناقص است.'});const name=String(customer.name||'').trim(),phone=String(customer.phone||'').trim(),address=String(customer.address||'').trim();if(!name||!phone||!address)return res.status(400).json({success:false,message:'نام، شماره تماس و آدرس الزامی است.'});const inv=readJson(INVENTORY_FILE,{});const clean=[];for(const i of items){const p=productMap.get(String(i.id));const q=Math.floor(Number(i.quantity)||0);const available=Number(inv[p?.id]??0);if(!p||q<1||q>available)return res.status(400).json({success:false,message:`موجودی «${p?.name||'کالا'}» کافی نیست.`});clean.push({id:p.id,name:p.name,brand:p.brand,price:Number(p.price||0),quantity:q,image:p.image});}const total=clean.reduce((s,i)=>s+i.price*i.quantity,0),inquiry=clean.some(i=>i.price<=0);const order={id:orderId(),customer:{name,phone,address},payment:payment==='online'?'online':'cod',items:clean,total,hasInquiryItems:inquiry,status:'جدید',createdAt:new Date().toISOString()};const orders=readJson(ORDERS_FILE,[]);orders.unshift(order);writeJson(ORDERS_FILE,orders);for(const i of clean){inv[i.id]=Math.max(0,Number(inv[i.id]??0)-i.quantity)}writeJson(INVENTORY_FILE,inv);backupData();res.status(201).json({success:true,orderId:order.id,total,inquiry,order})}catch(e){console.error('Order error:',e);res.status(500).json({success:false,message:'خطا در ثبت سفارش.'})}});
app.get('/api/orders',requireAdmin,(req,res)=>res.json({success:true,orders:readJson(ORDERS_FILE,[])}));
app.patch('/api/orders/:id',requireAdmin,(req,res)=>{const allowed=['جدید','در حال بررسی','آماده ارسال','ارسال شده','تحویل داده شده','لغو شده'];const status=String(req.body.status||'').trim();if(!allowed.includes(status))return res.status(400).json({success:false,message:'وضعیت نامعتبر است.'});const orders=readJson(ORDERS_FILE,[]),o=orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({success:false,message:'سفارش پیدا نشد.'});o.status=status;o.updatedAt=new Date().toISOString();writeJson(ORDERS_FILE,orders);backupData();res.json({success:true,order:o})});
app.get('/api/admin/backup',requireAdmin,(req,res)=>{const file=backupData();res.download(file,'firan-backup.json')});
app.get('/api/reviews',(req,res)=>{const id=String(req.query.productId||'');if(!validProducts.includes(id))return res.status(400).json({success:false,message:'محصول نامعتبر است.'});res.json({success:true,reviews:readJson(REVIEWS_FILE,[]).filter(x=>x.productId===id)})});
app.post('/api/reviews',(req,res)=>{const productId=String(req.body.productId||''),name=String(req.body.name||'').trim(),text=String(req.body.text||'').trim(),rating=Number(req.body.rating);if(!validProducts.includes(productId)||!name||!text||!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({success:false,message:'اطلاعات نظر نامعتبر است.'});const review={id:reviewId(),productId,name,rating,text,createdAt:new Date().toISOString()};const reviews=readJson(REVIEWS_FILE,[]);reviews.unshift(review);writeJson(REVIEWS_FILE,reviews);backupData();res.status(201).json({success:true,review})});
app.get('/api/admin/reviews',requireAdmin,(req,res)=>res.json({success:true,reviews:readJson(REVIEWS_FILE,[])}));
app.delete('/api/admin/reviews/:id',requireAdmin,(req,res)=>{const reviews=readJson(REVIEWS_FILE,[]),next=reviews.filter(x=>x.id!==req.params.id);if(next.length===reviews.length)return res.status(404).json({success:false,message:'نظر پیدا نشد.'});writeJson(REVIEWS_FILE,next);backupData();res.json({success:true})});
app.get('/admin.html',(req,res)=>getSession(req)?res.sendFile(path.join(__dirname,'admin.html')):res.redirect('/admin-login.html'));
app.post('/api/bot/ai-chat',async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(503).json({success:false,reply:'دستیار هوشمند فعلاً فعال نیست.'});const message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({success:false,reply:'لطفاً پیام خود را وارد کنید.'});const OpenAI=require('openai');const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await openai.responses.create({model:'gpt-5.6-luna',instructions:'تو دستیار فروشگاه هستی و به فارسی درباره محصولات و خرید کمک می‌کنی. اگر نمی‌دانی حدس نزن.',input:message});res.json({success:true,reply:r.output_text})}catch(e){console.error('OpenAI:',e);res.status(500).json({success:false,reply:'در ارتباط با دستیار هوشمند مشکلی پیش آمد.'})}});
app.use(express.static(__dirname));app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.use((req,res)=>req.path.startsWith('/api/')?res.status(404).json({success:false,message:'مسیر پیدا نشد.'}):res.status(404).sendFile(path.join(__dirname,'404.html')));
app.listen(PORT,()=>console.log(`Firan Kala server running: http://localhost:${PORT}`));